version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  # fail_on_warning: true
  
python:
  version: 3.6
  install:
    - requirements: 'requirements.txt'
    - requirements: 'docs/requirements.txt'
    - method: setuptools
      path: './'
