version: 1

# Build documentation in the doc/ directory with Sphinx
sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: true

# # Optionally build your docs in additional formats such as PDF and ePub
# formats: all

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.6
  install:
    - requirements: 'dev-requirements.txt'
    - requirements: 'requirements.txt'
    - requirements: 'doc/requirements.txt'
  setup_py_install: true
