language: python
python:
  - 3.6
install:
  - sudo apt update
  - pip3 install --upgrade pip
jobs:
  include:
    - stage: tests
      install:
        - pip install -r requirements.txt
        - pip install -r dev-requirements.txt
        - pip install flask
        - pip install pyjwt
      script:
        - export FLASK_APP=tests/server/app.py
        - flask run &
        - export PYTHONPATH=.
        - pytest -v --disable-warnings --cov=screamshot
      after_success:
        coveralls
    - stage: pylint
      install:
        - pip install pylint
      script:
        - pylint ./screamshot
