language: python
python:
  - "3.5"
install:
  - apt-get update
  - apt-get install python3-setuptools
  - pip install -r requirement.txt
  - pip install -r ./docker/checks/checks-requirement.txt
  - pip install flask
jobs:
  include:
    - stage: test
      script:
        - export FLASK_APP=tests/server/app.py
        - flask run &
        - python3 ./docker/checks/checks_command.py --no-mypy --no-pylint --no-unittest-parsing
    - stage: pylint
      script:
        - pylint .
