version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    command: "flask run -h 0.0.0.0"
  checks:
    depends_on:
      - "server"
    build:
      context: .
      dockerfile: ./docker/checks/Dockerfile
    volumes:
      - .:/screamshot
    command: "python3 docker/checks/checks_command.py --no-mypy --no-pylint"
