version: "3.3"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    network_mode: host
    command: "flask run"
    ports:
      - 5000:5000
  checks:
    depends_on:
      - "server"
    build:
      context: .
      dockerfile: ./docker/checks/Dockerfile
    network_mode: host
    environment:
      - PYTHONPATH=/screamshot
    volumes:
      - .:/screamshot
    command: "python3 scripts/checks_command.py"
